# Generated by Django 4.0 on 2022-05-30 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='cuisine',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='mealType',
        ),
    ]
